Import region
--------------

In [1]:
from sklearn import preprocessing
import numpy as np
import pandas as pd
from sklearn.preprocessing import Imputer

Example of standardization
---------------------------

In [2]:
X = np.array([[ 1., -1.,  2.],[ 2.,  0.,  0.],[ 0.,  1., -1.]])
print(X)

[[ 1. -1.  2.]
 [ 2.  0.  0.]
 [ 0.  1. -1.]]


In [3]:
X_scaled = preprocessing.scale(X)

In [4]:
X_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

Example of Replacing Missing value
---------------------------------

In [5]:
imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit([[1,2],[np.nan,3],[7,6]])
X = [[np.nan, 2], [6, np.nan], [7, 6]]
print(imp.transform(X))


[[ 4.          2.        ]
 [ 6.          3.66666667]
 [ 7.          6.        ]]


In [6]:
X_train = pd.read_csv('data/css_data.csv')

print(X_train.head())

   Unnamed: 0  @font-face  @keyframes  @media                       _id  \
0           0         NaN         NaN     NaN  59d256f52d3c2c06aa10fc69   
1           1         NaN         NaN     NaN  59d256f52d3c2c06aa10fc6a   
2           2         NaN         NaN     NaN  59d256f52d3c2c06aa10fc6b   
3           3         NaN         NaN     NaN  59d256f52d3c2c06aa10fc6c   
4           4         NaN         NaN     NaN  59d256f52d3c2c06aa10fc6d   

  align-content align-items align-self  all  \
0        normal      normal       auto  NaN   
1        normal      normal       auto  NaN   
2        normal      normal       auto  NaN   
3        normal      normal       auto  NaN   
4        normal      normal       auto  NaN   

                               animation   ...   unicode-bidi user-select  \
0  none 0s ease 0s 1 normal none running   ...         normal        text   
1  none 0s ease 0s 1 normal none running   ...         normal        text   
2  none 0s ease 0s 1 normal none ru

In [7]:
import numpy as np
import pandas as pd

input_file = "data/mydata.csv"


# comma delimited is the default
df = pd.read_csv(input_file, header = 0)

# for space delimited use:
# df = pd.read_csv(input_file, header = 0, delimiter = " ")

# for tab delimited use:
# df = pd.read_csv(input_file, header = 0, delimiter = "\t")

# put the original column names in a python list
original_headers = list(df.columns.values)

# remove the non-numeric columns
df = df._get_numeric_data()

# put the numeric column names in a python list
numeric_headers = list(df.columns.values)

# create a numpy array with the numeric values for input into scikit-learn
numpy_array = df.as_matrix()

# reverse the order of the columns
numeric_headers.reverse()
reverse_df = df[numeric_headers]

# write the reverse_df to an excel spreadsheet
reverse_df.to_excel('data/path_to_file.xls')