# Data Science Basic Tutorials

1. Numpy
2. Pandas

## 1. Numpy

Numpy arrays are great alternatives to Python Lists. Some of the key advantages of Numpy arrays are that they are fast, easy to work with, and give users the opportunity to perform calculations across entire arrays.

In the following example, you will first create two Python lists. Then, you will import the numpy package and create numpy arrays out of the newly created lists.

In [1]:
# Create 2 new lists height and weight
height = [1.87,  1.87, 1.82, 1.91, 1.90, 1.85]
weight = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

# Import the numpy package as np
import numpy as np

# Create 2 numpy arrays from height and weight
np_height = np.array(height)
np_weight = np.array(weight)

### Print out the type of np_height

In [2]:
print(type(np_height))

<class 'numpy.ndarray'>


### Element-wise calculations

In [3]:
# calculate bmi
bmi = np_weight / np_height**2

In [4]:
bmi

array([23.34925219, 27.88755755, 28.75558507, 25.48723993, 23.87257618,
       25.84368152])

### Subsetting

In [6]:
bmi > 25

array([False,  True,  True,  True, False,  True])

In [7]:
bmi[bmi > 25]

array([27.88755755, 28.75558507, 25.48723993, 25.84368152])

### Excercise

In [1]:
weight_kg = [81.65, 97.52, 95.25, 92.98, 86.18, 88.45]

import numpy as np

# Create a numpy array np_weight_kg from weight_kg
np_weight_kg = np.array(weight_kg)

# Create np_weight_lbs from np_weight_kg
np_weight_lbs = 2.2* np_weight_kg

# Print out np_weight_lbs
print(np_weight_lbs)

[179.63  214.544 209.55  204.556 189.596 194.59 ]


## 2. Pandas Basics

### 2.1. DataFrame

DataFrame is built on the Numpy package and its key data structure is called the DataFrame. DataFrame allow you to store and manipulate tabular data in rows of observations and columns of variables.

In [2]:
dict = {"country": ["Brazil", "Russia", "India", "China", "South Africa"],
       "capital": ["Brasilia", "Moscow", "New Dehli", "Beijing", "Pretoria"],
       "area": [8.516, 17.10, 3.286, 9.597, 1.221],
       "population": [200.4, 143.5, 1252, 1357, 52.98] }

In [3]:
import pandas as pd
brics = pd.DataFrame(dict)
print(brics)

        country    capital    area  population
0        Brazil   Brasilia   8.516      200.40
1        Russia     Moscow  17.100      143.50
2         India  New Dehli   3.286     1252.00
3         China    Beijing   9.597     1357.00
4  South Africa   Pretoria   1.221       52.98


#### Set the index for brics

In [4]:
brics.index = ['BR',"RU",'IN','CH','SA']

print(brics)

         country    capital    area  population
BR        Brazil   Brasilia   8.516      200.40
RU        Russia     Moscow  17.100      143.50
IN         India  New Dehli   3.286     1252.00
CH         China    Beijing   9.597     1357.00
SA  South Africa   Pretoria   1.221       52.98


### Read data from csv file